// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

#ifndef PROTOBUF_rpc_2eproto__INCLUDED
#define PROTOBUF_rpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace muduo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_rpc_2eproto();
void protobuf_AssignDesc_rpc_2eproto();
void protobuf_ShutdownFile_rpc_2eproto();

class RpcMessage;

enum MessageType {
  REQUEST = 1,
  RESPONSE = 2,
  ERROR = 3
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = REQUEST;
const MessageType MessageType_MAX = ERROR;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
enum ErrorCode {
  WRONG_PROTO = 1,
  NO_SERVICE = 2,
  NO_METHOD = 3,
  INVALID_REQUEST = 4,
  INVALID_RESPONSE = 5
};
bool ErrorCode_IsValid(int value);
const ErrorCode ErrorCode_MIN = WRONG_PROTO;
const ErrorCode ErrorCode_MAX = INVALID_RESPONSE;
const int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor();
inline const ::std::string& ErrorCode_Name(ErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ErrorCode_descriptor(), value);
}
inline bool ErrorCode_Parse(
    const ::std::string& name, ErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
// ===================================================================

class RpcMessage : public ::google::protobuf::Message {
 public:
  RpcMessage();
  virtual ~RpcMessage();
  
  RpcMessage(const RpcMessage& from);
  
  inline RpcMessage& operator=(const RpcMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RpcMessage& default_instance();
  
  void Swap(RpcMessage* other);
  
  // implements Message ----------------------------------------------
  
  RpcMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RpcMessage& from);
  void MergeFrom(const RpcMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .muduo.MessageType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline muduo::MessageType type() const;
  inline void set_type(muduo::MessageType value);
  
  // required fixed64 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);
  
  // optional string service = 3;
  inline bool has_service() const;
  inline void clear_service();
  static const int kServiceFieldNumber = 3;
  inline const ::std::string& service() const;
  inline void set_service(const ::std::string& value);
  inline void set_service(const char* value);
  inline void set_service(const char* value, size_t size);
  inline ::std::string* mutable_service();
  
  // optional string method = 4;
  inline bool has_method() const;
  inline void clear_method();
  static const int kMethodFieldNumber = 4;
  inline const ::std::string& method() const;
  inline void set_method(const ::std::string& value);
  inline void set_method(const char* value);
  inline void set_method(const char* value, size_t size);
  inline ::std::string* mutable_method();
  
  // optional bytes request = 5;
  inline bool has_request() const;
  inline void clear_request();
  static const int kRequestFieldNumber = 5;
  inline const ::std::string& request() const;
  inline void set_request(const ::std::string& value);
  inline void set_request(const char* value);
  inline void set_request(const void* value, size_t size);
  inline ::std::string* mutable_request();
  
  // optional bytes response = 6;
  inline bool has_response() const;
  inline void clear_response();
  static const int kResponseFieldNumber = 6;
  inline const ::std::string& response() const;
  inline void set_response(const ::std::string& value);
  inline void set_response(const char* value);
  inline void set_response(const void* value, size_t size);
  inline ::std::string* mutable_response();
  
  // optional .muduo.ErrorCode error = 7;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 7;
  inline muduo::ErrorCode error() const;
  inline void set_error(muduo::ErrorCode value);
  
  // @@protoc_insertion_point(class_scope:muduo.RpcMessage)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  int type_;
  ::google::protobuf::uint64 id_;
  ::std::string* service_;
  static const ::std::string _default_service_;
  ::std::string* method_;
  static const ::std::string _default_method_;
  ::std::string* request_;
  static const ::std::string _default_request_;
  ::std::string* response_;
  static const ::std::string _default_response_;
  int error_;
  friend void  protobuf_AddDesc_rpc_2eproto();
  friend void protobuf_AssignDesc_rpc_2eproto();
  friend void protobuf_ShutdownFile_rpc_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static RpcMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// RpcMessage

// required .muduo.MessageType type = 1;
inline bool RpcMessage::has_type() const {
  return _has_bit(0);
}
inline void RpcMessage::clear_type() {
  type_ = 1;
  _clear_bit(0);
}
inline muduo::MessageType RpcMessage::type() const {
  return static_cast< muduo::MessageType >(type_);
}
inline void RpcMessage::set_type(muduo::MessageType value) {
  GOOGLE_DCHECK(muduo::MessageType_IsValid(value));
  _set_bit(0);
  type_ = value;
}

// required fixed64 id = 2;
inline bool RpcMessage::has_id() const {
  return _has_bit(1);
}
inline void RpcMessage::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  _clear_bit(1);
}
inline ::google::protobuf::uint64 RpcMessage::id() const {
  return id_;
}
inline void RpcMessage::set_id(::google::protobuf::uint64 value) {
  _set_bit(1);
  id_ = value;
}

// optional string service = 3;
inline bool RpcMessage::has_service() const {
  return _has_bit(2);
}
inline void RpcMessage::clear_service() {
  if (service_ != &_default_service_) {
    service_->clear();
  }
  _clear_bit(2);
}
inline const ::std::string& RpcMessage::service() const {
  return *service_;
}
inline void RpcMessage::set_service(const ::std::string& value) {
  _set_bit(2);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(value);
}
inline void RpcMessage::set_service(const char* value) {
  _set_bit(2);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(value);
}
inline void RpcMessage::set_service(const char* value, size_t size) {
  _set_bit(2);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RpcMessage::mutable_service() {
  _set_bit(2);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  return service_;
}

// optional string method = 4;
inline bool RpcMessage::has_method() const {
  return _has_bit(3);
}
inline void RpcMessage::clear_method() {
  if (method_ != &_default_method_) {
    method_->clear();
  }
  _clear_bit(3);
}
inline const ::std::string& RpcMessage::method() const {
  return *method_;
}
inline void RpcMessage::set_method(const ::std::string& value) {
  _set_bit(3);
  if (method_ == &_default_method_) {
    method_ = new ::std::string;
  }
  method_->assign(value);
}
inline void RpcMessage::set_method(const char* value) {
  _set_bit(3);
  if (method_ == &_default_method_) {
    method_ = new ::std::string;
  }
  method_->assign(value);
}
inline void RpcMessage::set_method(const char* value, size_t size) {
  _set_bit(3);
  if (method_ == &_default_method_) {
    method_ = new ::std::string;
  }
  method_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RpcMessage::mutable_method() {
  _set_bit(3);
  if (method_ == &_default_method_) {
    method_ = new ::std::string;
  }
  return method_;
}

// optional bytes request = 5;
inline bool RpcMessage::has_request() const {
  return _has_bit(4);
}
inline void RpcMessage::clear_request() {
  if (request_ != &_default_request_) {
    request_->clear();
  }
  _clear_bit(4);
}
inline const ::std::string& RpcMessage::request() const {
  return *request_;
}
inline void RpcMessage::set_request(const ::std::string& value) {
  _set_bit(4);
  if (request_ == &_default_request_) {
    request_ = new ::std::string;
  }
  request_->assign(value);
}
inline void RpcMessage::set_request(const char* value) {
  _set_bit(4);
  if (request_ == &_default_request_) {
    request_ = new ::std::string;
  }
  request_->assign(value);
}
inline void RpcMessage::set_request(const void* value, size_t size) {
  _set_bit(4);
  if (request_ == &_default_request_) {
    request_ = new ::std::string;
  }
  request_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RpcMessage::mutable_request() {
  _set_bit(4);
  if (request_ == &_default_request_) {
    request_ = new ::std::string;
  }
  return request_;
}

// optional bytes response = 6;
inline bool RpcMessage::has_response() const {
  return _has_bit(5);
}
inline void RpcMessage::clear_response() {
  if (response_ != &_default_response_) {
    response_->clear();
  }
  _clear_bit(5);
}
inline const ::std::string& RpcMessage::response() const {
  return *response_;
}
inline void RpcMessage::set_response(const ::std::string& value) {
  _set_bit(5);
  if (response_ == &_default_response_) {
    response_ = new ::std::string;
  }
  response_->assign(value);
}
inline void RpcMessage::set_response(const char* value) {
  _set_bit(5);
  if (response_ == &_default_response_) {
    response_ = new ::std::string;
  }
  response_->assign(value);
}
inline void RpcMessage::set_response(const void* value, size_t size) {
  _set_bit(5);
  if (response_ == &_default_response_) {
    response_ = new ::std::string;
  }
  response_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RpcMessage::mutable_response() {
  _set_bit(5);
  if (response_ == &_default_response_) {
    response_ = new ::std::string;
  }
  return response_;
}

// optional .muduo.ErrorCode error = 7;
inline bool RpcMessage::has_error() const {
  return _has_bit(6);
}
inline void RpcMessage::clear_error() {
  error_ = 1;
  _clear_bit(6);
}
inline muduo::ErrorCode RpcMessage::error() const {
  return static_cast< muduo::ErrorCode >(error_);
}
inline void RpcMessage::set_error(muduo::ErrorCode value) {
  GOOGLE_DCHECK(muduo::ErrorCode_IsValid(value));
  _set_bit(6);
  error_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace muduo

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< muduo::MessageType>() {
  return muduo::MessageType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< muduo::ErrorCode>() {
  return muduo::ErrorCode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rpc_2eproto__INCLUDED
